spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Qkrehdwns1!
  jpa:
    hibernate:
      ddl-auto: create   # ???. ??? migration ??
    show-sql: true
    properties:
      hibernate.format_sql: true
server:
  port: 8080

